site_name: MLOps
repo_url: https://github.com/itsdaveba/mlops
edit_uri: edit/main/docs
site_description: MLOps Documentation.
site_author: David Barragan

theme: readthedocs

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - Gettin Started: getting_started.md
  - Configuration: config/config.md
  - API Documentation: app/api.md
  - Reference:
    - main: mlops/main.md
    - data: mlops/data.md
    - train: mlops/train.md
    - utils: mlops/utils.md