name: documentation
on:
  push:
    branches: main
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install -e .[test]
      - run: dvc pull
      - run: pytest
  feature-engineering:
    needs: test-code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install -e .
      - run: dvc pull
      - run: mlops feature-engineering
      - run: dvc push
  train-model:
    needs: feature-engineering
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install -e .
      - run: dvc pull
      - run: mlops train-model
      - run: dvc push
  documentation:
    needs: test-code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install -e .[docs]
      - run: mkdocs gh-deploy --force