name: documentation
on:
  push:
    branches: main
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: python -m pip install pandas
      - run: pip show pandas
      - uses: actions/upload-artifact@v2
        with:
          name: python-modules
          path: /usr/local/lib/python3.10/site-packages
      - run: rm data/api_dataset.csv.dvc
      - run: rm models/api_metrics.json.dvc
      - run: rm models/api.joblib.dvc
      - run: dvc pull
      - run: pytest
  feature-engineering:
    needs: test-code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - uses: actions/download-artifact@v2
        with:
          name: python-modules
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install -e .
      - run: rm data/api_dataset.csv.dvc
      - run: rm models/api_metrics.json.dvc
      - run: rm models/api.joblib.dvc
      - run: dvc pull
      - run: mlops feature-engineering
  test-data:
    needs: feature-engineering
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install -e .[test]
      - run: rm models/api_metrics.json.dvc
      - run: rm models/api.joblib.dvc
      - run: dvc pull
      - run: cd tests && great_expectations checkpoint run credit_risk
      - run: cd tests && great_expectations checkpoint run api
  train-model:
    needs: feature-engineering
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install -e .
      - run: rm models/api_metrics.json.dvc
      - run: rm models/api.joblib.dvc
      - run: dvc pull
      - run: mlops train-model
      - run: cat models/api_metrics.json
  documentation:
    needs: [test-code, test-data]
    runs-on: ubuntu-latest
    environment: 'prod'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install -e .[docs]
      - run: mkdocs gh-deploy --force